### ISSUE TITLE
Compile against modern .NET

### ISSUE THREAD

**Issue by MADxingjin** [thomotron/Phinix#74]
## Description
We could switch commons project used in both standalone server and ingame client side from build against **.NET Framework 4.7.2** to **.NET Standard 2.0** which **should be**(Not tested yet but documents says so) acceptable by unity engine the game uses while also can be used as dependencies on modern versions of .NET .
Then port server to **.NET 6** to drop mono requirements and improve its performance.
## Additional context
After digging the code a little bit, my only concern is protobuf serialized messages.
I`ve already started a WIP project attempting to recompile commons against .NET standard and test its binary compatible or not.

[.NET Standard] (https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-0)

**Comment by MADxingjin** [comment]
Update:
I cloned this repo and used update-assistant to update all commons to .NET Standard 2.1 and Server to .NET 6.
No major problems found. Server is alive using .NET 6 and runs well on my localhost.
HOWEVER I failed to compile client in vs2022 likely due to some error in its csproj.

**Comment by thomotron** [comment]
Nice! I suspect that the update assistant probably ruined the csproj somehow, although it does have several hacky bits in there to get it to support building against both 1.3 and 1.4 versions of RimWorld with the flip of a switch. I don't use VS myself and I haven't been asked to upgrade the project file given MSBuild reads it in fine.

I don't have any problem with migrating all the non-client projects over to .NET 6/Standard 2.0 so long as it all works within Unity. As you said this'll be great for the server since we can just take mono out of the equation.

As for protobuf, it should all be binary-compatible by design, but yes it's also worth testing.

**Comment by thomotron** [comment]
I have some big changes happening IRL over the next week or two so I may or may not get around to testing this myself. If you do manage to get this working cleanly then you're welcome to put a PR through for it!

**Comment by MADxingjin** [comment]
Update:
Client **FAILED** to load.
I managed to compile client using commons compile against .NET Standard and it passed compile stage, but Unity engine shipped with the game is not bundled with .NET Standard DLLs so commons compiled against .NET Standard will **FAIL** to load, broke the dependency chain that client requires.

Wonder if i can share those source files under two sets of csproj for different compile target.
However this may lead to many issues in following feature development and hunting bugs.


|csproj|Compiled against|compile|run
|---|---|---|---|
|Commons+Util|.NET Standard 2.0  |PASS||
|Server|.NET 6|PASS|PASS
|Client|.NET Framework 4.7.2|PASS|**FAIL**|
